config/routes.rb
Rails.application.routes.draw do
  resources :themes
  resources :events

  root to: 'pages#home'

  devise_for :users

  resources :users, only: [:show]
  resources :profiles, only: [:new, :edit, :create, :update]
  resources :events, except: [:destroy]

  namespace :api do
    resources :events
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true
  has_and_belongs_to_many :themes

  has_many :photos, dependent: :destroy
  has_many :registration, dependent: :destroy

  has_many :guests, through: :registration, source: :user

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 500}
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/theme.rb
class Theme < ApplicationRecord
  validates :name, presence: true, uniqueness: true
   has_and_belongs_to_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, dependent: :destroy

  has_many :events, dependent: :destroy
  has_many :registration, dependent: :destroy

  has_many :registerd_events, through: :registration, source: :event

  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end
end

app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    render status: 200, json: {
      events: Event.all
    }.to_json
  end

  def show
    event = Event.find(event_params[:id])

    render status: 200, json: {
      event: event
    }.to_json
  end



  def create
   event = event.new(event_params)

   if event.save
     render status: 201, json: {
       message: "event successfully created",
       event: event
     }.to_json
   else
     render status: 422, json: {
       errors: event.errors
     }.to_json
   end
 end

 def destroy
   event = Event.find(event_params[:id])
   event.destroy

   render status: 200, json: {
     message: "Event has been deleted"
   }.to_json
 end

   private
 def event_params
   event_params.require(:event).permit(:name,
   :description, :location, :price, :capacity,
   :includes_food, :includes_drinks, :starts_at, :ends_at,
   :active, :user ,:themes)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :event, only: [:show, :edit, :update]
   before_action :authenticate_user!, except: [:show]



   def index
     @events = current_user.events
   end



   def show
     @themes = event.themes
     @photos = event.photos
   end



   def new
     @event = current_user.events.build
   end



   def create
     @event = current_user.events.build(event_params)

     if @event.save

       image_params.each do |image|
         @event.photos.create(image: image)
       end

       redirect_to edit_event_path(@event), notice: "Event successfully created"
     else
       render :new
     end
   end



   def edit
     if current_user.id == @event.user.id
       @photos = @event.photos
     else
       redirect_to root_path, notice: "You don't have permission."
     end
   end



  def update
    if @event.update(event_params)
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to edit_event_path(@event), notice: "Event successfully updated"
    else
      render :edit
    end
  end


   private

   def event
     @event = Event.find(params[:id])
   end

   def event_params
     params
       .require(:event)
       .permit(
         :name, :description, :location, :price, :capacity, :includes_food,
         :includes_drinks, :starts_at, :ends_at, :active, :user_id, :created_at, :updated_at)
   end
  end

  def image_params
    params[:images].present? ? params.require(:images) : []
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
    before_action :authenticate_user!

    def new
      @profile = Profile.new
    end

    def create
      @profile = current_user.build_profile(profile_params)

      if @profile.save
        redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @profile.update(profile_params)
        redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
      else
        render :edit
      end
    end

    private
      def set_profile
        @profile = current_user.profile
      end

      def profile_params
        params.require(:profile).permit(:first_name, :last_name, :bio)
      end
  end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
      @user = User.find(params[:id])
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event,html: {multipart:true} do |f| %>

<div class="form-group">

  <label>Name Event</label><br><br>
  <%= f.text_area :name, rows: 1, placeholder: "Name Your Event", class: "form-control" %>
</div>

  <div class="form-group">
    <label>Event Type</label><br>
    <%= f.select :name, [["Tech", "Tech"], ["Familie", "Familie"], ["Sport & Health", "Sport & Health"]], id: "event_type", prompt: "Select event type", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Number of People</label><br>
    <%= f.select :capacity, [["2-5", 0], ["6-8", 1], ["9-12", 2], ["12-15", 3], ["15-18", 4], ["19 +", 5]], prompt: "Select number of people", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Price Range</label><br>
    <%= f.select :price, [["€ 10", 10], ["€ 20", 20], ["€ 30", 30], ["€ 40+", 40]], prompt: "Select Price Range", class: "form-control" %>
  </div>


  <div class="form-group">
    <label>Description</label><br>
    <%= f.text_area :description, rows: 5, placeholder: "Say something about your event", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Location</label>
    <%= f.text_field :location, placeholder: "Location", class: "form-control" %>
  </div>

  <label>Amenities</label>

  <div class="form-group">
    <%= f.check_box :includes_drinks %> Includes Drinks
  </div>
  <div class="form-group">
    <%= f.check_box :includes_food %> Includes Food
  </div>
  <div class="form-group">
    <%= f.check_box :active %> Active User
  </div>

  <label>Publish this place?</label>

  <div class="form-group">
    <%= f.check_box :active %> Active
  </div>

  <label>Photos</label>

<div class="form-group">
  <span class="btn btn-default">
    Upload Photos
    <%= file_field_tag "images[]", type: :file, multiple: true %>
  </span>
</div>

<div id="photos">
  <%= render 'photos/list' %>
</div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
      <% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit Event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", events_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", events_path, class: "sidebar-link" %></li>
    </ul>
  </div>

  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Listings
      </div>

      <div class="panel-body">
        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= event.name %></h4>

          </div>
          <div class="col-md-3 right">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
          </div>

        </div>
        <% end %>
      </div>
    </div>

    <%= link_to "Add new event", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
 <div class="panel panel-default">
  <div class="panel-heading">
    Add a new Event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><%= @event.name %></div>

  <div class="panel-body">


    <p>Host: <%= @event.user.email %></p>

    <!-- Main Info -->
    <h4>Main Info</h4>
    <p>Event Type: <%= @event.name %></p>
    <p><%= @event.description %> <%= @event.description %></p>
    <p><%= @event.capacity %> <%= @event.capacity > 1 ? "Number of Guest" : "Number of Guest" %></p>
    <p><%= @event.price %> <%= @event.price > 1 ? "Price" : "Price" %></p>

    <!-- About -->
    <h4>About</h4>
    <p><%= @event.description %></p>


    <!-- Amenities -->
    <h4>Amenities</h4>
    <ul class="amenities">
      <li><%= !@event.includes_food ? ("<s>Food?</s>").html_safe : "Including Food" %></li>
      <li><%= !@event.includes_drinks ? ("<s>Drinks</s>").html_safe : "Including Drinks" %></li>
      <li><%= !@event.active ? ("<s>Active</s>").html_safe : "Active" %></li>
    </ul>
   </div>

   <!-- Photos -->
   <h4>Photos</h4>
   <% @event.photos.each do |photo| %>
     <%= image_tag photo.image %>
   <% end %>

   <%= link_to "Back", events_path, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>

      <div class="container"><%= notice %></div>
      <div class="container"><%= alert %></div>

    <div class="container">
    <%= yield %>
    </div>
</body>
</html>

app/views/pages/home.html.erb
<body>
  <h1>CODAISSEURbnb</h1>
  <p>Find me in app/views/pages/home.html.erb</p>
</body>

app/views/photos/_list.html.erb
<% if @photos %>
  <% @photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= image_tag photo.image %>
      </div>
      <div class="panel-body">
        <span class="btn btn-default">Delete</span>
      </div>
    </div>
  <% end %>
<% end %>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Bio</label>
    <%= f.text_area :bio, rows: 5, placeholder: "Say something about yourself", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurbnb", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
    <%= current_user.has_profile? ? current_user.full_name : current_user.email  %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li><%= link_to "Your Listings", events_path %></li>
              <li role="separator" class="divider"></li>

              <% if current_user.has_profile? %>
                <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
              <% else %>
                <li><%= link_to "Create Profile", new_profile_path %></li>
              <% end %>
              <li><%= link_to "Edit Password", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>

          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>